export const list = [
  {
    title: 'Make a tasty coofee ☕ !! ',
    paragraph: [
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
    ],
    imageLink: 'https://picsum.photos/id/425/400/400',
  },
  {
    title: "Fraise🍓 c'est du delice",
    paragraph: [
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
    ],
    imageLink: 'https://picsum.photos/id/429/400/400',
  },
  {
    title: '  De la salade🍲 ?  ',
    paragraph: [
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
    ],
    imageLink: 'https://picsum.photos/id/488/400/400',
  },
  {
    title: '  Raisin 🍇   ',
    paragraph: [
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
    ],
    imageLink: 'https://picsum.photos/id/674/400/400',
  },
  {
    title: '  Cookies 🍪   ',
    paragraph: [
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
    ],
    imageLink: 'https://picsum.photos/id/835/400/400',
  },
  {
    title: '  Pear 🍐 ?  ',
    paragraph: [
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
      'lorem ipsum dolor sirt',
    ],
    imageLink: 'https://picsum.photos/id/999/400/400',
  },
];
